version: 2.1

jobs:
  download_video:
    docker:
      - image: python:3.11-slim
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install -y ffmpeg curl
            pip install yt-dlp requests
      - run:
          name: Download video
          command: |
            echo "Starting video download..."
            mkdir -p downloads
            cd downloads
            yt-dlp --format "best[height<=720]/best" --output "%(id)s.%(ext)s" --no-warnings --retries 3 --fragment-retries 3 "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
            ls -la
            echo "Download completed successfully"
      - store_artifacts:
          path: downloads

workflows:
  download-and-upload:
    jobs:
      - download_video